/*
 * TSTool-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.hanke.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * AccessParameterValuesDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-28T12:57:13.425Z")
public class AccessParameterValuesDto {
    @SerializedName("tsComposedKey")
    private TimeSeriesComposedKey tsComposedKey = null;

    @SerializedName("tsraster")
    private TimeSeriesRaster tsraster = null;

    public AccessParameterValuesDto tsComposedKey(TimeSeriesComposedKey tsComposedKey) {
        this.tsComposedKey = tsComposedKey;
        return this;
    }

    /**
     * Get tsComposedKey
     *
     * @return tsComposedKey
     **/
    @ApiModelProperty(value = "")
    public TimeSeriesComposedKey getTsComposedKey() {
        return tsComposedKey;
    }

    public void setTsComposedKey(TimeSeriesComposedKey tsComposedKey) {
        this.tsComposedKey = tsComposedKey;
    }

    public AccessParameterValuesDto tsraster(TimeSeriesRaster tsraster) {
        this.tsraster = tsraster;
        return this;
    }

    /**
     * Get tsraster
     *
     * @return tsraster
     **/
    @ApiModelProperty(value = "")
    public TimeSeriesRaster getTsraster() {
        return tsraster;
    }

    public void setTsraster(TimeSeriesRaster tsraster) {
        this.tsraster = tsraster;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AccessParameterValuesDto accessParameterValuesDto = (AccessParameterValuesDto) o;
        return Objects.equals(this.tsComposedKey, accessParameterValuesDto.tsComposedKey) &&
                Objects.equals(this.tsraster, accessParameterValuesDto.tsraster);
    }

    @Override
    public int hashCode() {
        return Objects.hash(tsComposedKey, tsraster);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AccessParameterValuesDto {\n");

        sb.append("    tsComposedKey: ").append(toIndentedString(tsComposedKey)).append("\n");
        sb.append("    tsraster: ").append(toIndentedString(tsraster)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

