/*
 * TSTool-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.hanke.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * PeriodicTimeseries
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-28T12:57:13.425Z")
public class PeriodicTimeseries {
    @SerializedName("timeSeriesHead")
    private TimeSeriesHead timeSeriesHead = null;

    @SerializedName("timeSeriesValues")
    private Object timeSeriesValues = null;

    public PeriodicTimeseries timeSeriesHead(TimeSeriesHead timeSeriesHead) {
        this.timeSeriesHead = timeSeriesHead;
        return this;
    }

    /**
     * Get timeSeriesHead
     *
     * @return timeSeriesHead
     **/
    @ApiModelProperty(value = "")
    public TimeSeriesHead getTimeSeriesHead() {
        return timeSeriesHead;
    }

    public void setTimeSeriesHead(TimeSeriesHead timeSeriesHead) {
        this.timeSeriesHead = timeSeriesHead;
    }

    public PeriodicTimeseries timeSeriesValues(Object timeSeriesValues) {
        this.timeSeriesValues = timeSeriesValues;
        return this;
    }

    /**
     * Get timeSeriesValues
     *
     * @return timeSeriesValues
     **/
    @ApiModelProperty(value = "")
    public Object getTimeSeriesValues() {
        return timeSeriesValues;
    }

    public void setTimeSeriesValues(Object timeSeriesValues) {
        this.timeSeriesValues = timeSeriesValues;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PeriodicTimeseries periodicTimeseries = (PeriodicTimeseries) o;
        return Objects.equals(this.timeSeriesHead, periodicTimeseries.timeSeriesHead) &&
                Objects.equals(this.timeSeriesValues, periodicTimeseries.timeSeriesValues);
    }

    @Override
    public int hashCode() {
        return Objects.hash(timeSeriesHead, timeSeriesValues);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PeriodicTimeseries {\n");

        sb.append("    timeSeriesHead: ").append(toIndentedString(timeSeriesHead)).append("\n");
        sb.append("    timeSeriesValues: ").append(toIndentedString(timeSeriesValues)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

