/*
 * TSTool-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.hanke.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * PersistenceParameterValuesDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-28T12:57:13.425Z")
public class PersistenceParameterValuesDto {
    @SerializedName("tsComposedKey")
    private TimeSeriesComposedKey tsComposedKey = null;

    @SerializedName("tsvalues")
    private List<TimeSeriesValue> tsvalues = null;

    public PersistenceParameterValuesDto tsComposedKey(TimeSeriesComposedKey tsComposedKey) {
        this.tsComposedKey = tsComposedKey;
        return this;
    }

    /**
     * Get tsComposedKey
     *
     * @return tsComposedKey
     **/
    @ApiModelProperty(value = "")
    public TimeSeriesComposedKey getTsComposedKey() {
        return tsComposedKey;
    }

    public void setTsComposedKey(TimeSeriesComposedKey tsComposedKey) {
        this.tsComposedKey = tsComposedKey;
    }

    public PersistenceParameterValuesDto tsvalues(List<TimeSeriesValue> tsvalues) {
        this.tsvalues = tsvalues;
        return this;
    }

    public PersistenceParameterValuesDto addTsvaluesItem(TimeSeriesValue tsvaluesItem) {
        if (this.tsvalues == null) {
            this.tsvalues = new ArrayList<TimeSeriesValue>();
        }
        this.tsvalues.add(tsvaluesItem);
        return this;
    }

    /**
     * Get tsvalues
     *
     * @return tsvalues
     **/
    @ApiModelProperty(value = "")
    public List<TimeSeriesValue> getTsvalues() {
        return tsvalues;
    }

    public void setTsvalues(List<TimeSeriesValue> tsvalues) {
        this.tsvalues = tsvalues;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PersistenceParameterValuesDto persistenceParameterValuesDto = (PersistenceParameterValuesDto) o;
        return Objects.equals(this.tsComposedKey, persistenceParameterValuesDto.tsComposedKey) &&
                Objects.equals(this.tsvalues, persistenceParameterValuesDto.tsvalues);
    }

    @Override
    public int hashCode() {
        return Objects.hash(tsComposedKey, tsvalues);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PersistenceParameterValuesDto {\n");

        sb.append("    tsComposedKey: ").append(toIndentedString(tsComposedKey)).append("\n");
        sb.append("    tsvalues: ").append(toIndentedString(tsvalues)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

