/*
 * TSTool-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.hanke.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets TimeSeriesRaster
 */
@JsonAdapter(TimeSeriesRaster.Adapter.class)
public enum TimeSeriesRaster {

    PT15M("PT15M"),

    PT15S("PT15S"),

    PT1H("PT1H"),

    PT1D("PT1D");

    private final String value;

    TimeSeriesRaster(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static TimeSeriesRaster fromValue(String text) {
        for (TimeSeriesRaster b : TimeSeriesRaster.values()) {
            if (String.valueOf(b.value).equals(text)) {
                return b;
            }
        }
        return null;
    }

    public static class Adapter extends TypeAdapter<TimeSeriesRaster> {
        @Override
        public void write(final JsonWriter jsonWriter, final TimeSeriesRaster enumeration) throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public TimeSeriesRaster read(final JsonReader jsonReader) throws IOException {
            String value = jsonReader.nextString();
            return TimeSeriesRaster.fromValue(String.valueOf(value));
        }
    }
}

