/*
 * TSTool-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.hanke.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets TimeSeriesUnit
 */
@JsonAdapter(TimeSeriesUnit.Adapter.class)
public enum TimeSeriesUnit {

    MW("mW"),

    MWH("mWH"),

    KW("kW"),

    KWH("kWH"),

    EUR("EUR"),

    GRADCELCIUS("GRADCELCIUS"),

    LITERPROMINUTE("LITERPROMINUTE"),

    BAR("BAR"),

    STATUS("STATUS"),

    STUNDEN("STUNDEN"),

    MINUTEN("MINUTEN"),

    SEKUNDEN("SEKUNDEN"),

    PROZENT("PROZENT"),

    ANZAHL("ANZAHL");

    private final String value;

    TimeSeriesUnit(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static TimeSeriesUnit fromValue(String text) {
        for (TimeSeriesUnit b : TimeSeriesUnit.values()) {
            if (String.valueOf(b.value).equals(text)) {
                return b;
            }
        }
        return null;
    }

    public static class Adapter extends TypeAdapter<TimeSeriesUnit> {
        @Override
        public void write(final JsonWriter jsonWriter, final TimeSeriesUnit enumeration) throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public TimeSeriesUnit read(final JsonReader jsonReader) throws IOException {
            String value = jsonReader.nextString();
            return TimeSeriesUnit.fromValue(String.valueOf(value));
        }
    }
}

