/*
 * TSTool-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.hanke.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Timeseries
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-28T12:57:13.425Z")
public class Timeseries {
    @SerializedName("timeSeriesHead")
    private TimeSeriesHead timeSeriesHead = null;

    @SerializedName("timeSeriesValues")
    private List<TimeSeriesValue> timeSeriesValues = null;

    public Timeseries timeSeriesHead(TimeSeriesHead timeSeriesHead) {
        this.timeSeriesHead = timeSeriesHead;
        return this;
    }

    /**
     * Get timeSeriesHead
     *
     * @return timeSeriesHead
     **/
    @ApiModelProperty(value = "")
    public TimeSeriesHead getTimeSeriesHead() {
        return timeSeriesHead;
    }

    public void setTimeSeriesHead(TimeSeriesHead timeSeriesHead) {
        this.timeSeriesHead = timeSeriesHead;
    }

    public Timeseries timeSeriesValues(List<TimeSeriesValue> timeSeriesValues) {
        this.timeSeriesValues = timeSeriesValues;
        return this;
    }

    public Timeseries addTimeSeriesValuesItem(TimeSeriesValue timeSeriesValuesItem) {
        if (this.timeSeriesValues == null) {
            this.timeSeriesValues = new ArrayList<TimeSeriesValue>();
        }
        this.timeSeriesValues.add(timeSeriesValuesItem);
        return this;
    }

    /**
     * Get timeSeriesValues
     *
     * @return timeSeriesValues
     **/
    @ApiModelProperty(value = "")
    public List<TimeSeriesValue> getTimeSeriesValues() {
        return timeSeriesValues;
    }

    public void setTimeSeriesValues(List<TimeSeriesValue> timeSeriesValues) {
        this.timeSeriesValues = timeSeriesValues;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Timeseries timeseries = (Timeseries) o;
        return Objects.equals(this.timeSeriesHead, timeseries.timeSeriesHead) &&
                Objects.equals(this.timeSeriesValues, timeseries.timeSeriesValues);
    }

    @Override
    public int hashCode() {
        return Objects.hash(timeSeriesHead, timeSeriesValues);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Timeseries {\n");

        sb.append("    timeSeriesHead: ").append(toIndentedString(timeSeriesHead)).append("\n");
        sb.append("    timeSeriesValues: ").append(toIndentedString(timeSeriesValues)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

