/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.hanke.arnim.TSServer.api;

import de.hanke.arnim.TSServer.model.AccessParameterValuesDto;
import de.hanke.arnim.TSServer.model.DeleteParameterValuesDto;
import de.hanke.arnim.TSServer.model.Error;
import java.util.List;
import de.hanke.arnim.TSServer.model.PersistenceParameterValuesDto;
import de.hanke.arnim.TSServer.model.Timeseries;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-06-01T11:50:12.361Z")

@Api(value = "timeseriesValuesByParameters", description = "the timeseriesValuesByParameters API")
@RequestMapping(value = "/TSTool-api")
public interface TimeseriesValuesByParametersApi {

    @ApiOperation(value = "Removes values of given Timeseries. The Timeseries must exists!", nickname = "deleteTimeseriesValuesByDeleteParameterValuesDtos", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 401, message = "unauthorized", response = Error.class),
        @ApiResponse(code = 404, message = "resource not found", response = Error.class),
        @ApiResponse(code = 200, message = "error", response = Error.class) })
    @RequestMapping(value = "/timeseriesValuesByParameters",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteTimeseriesValuesByDeleteParameterValuesDtos(@ApiParam(value = ""  )  @Valid @RequestBody List<DeleteParameterValuesDto> deleteParametersValuesDto,@ApiParam(value = "") @Valid @RequestParam(value = "interval", required = false) String interval);


    @ApiOperation(value = "Get timeseries values for requested AccessParameterValuesDtos", nickname = "getTimeseriesValuesByAccessParameterValuesDtos", notes = "", response = Timeseries.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Timeseries.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "unauthorized", response = Error.class),
        @ApiResponse(code = 404, message = "resource not found", response = Error.class),
        @ApiResponse(code = 200, message = "error", response = Error.class) })
    @RequestMapping(value = "/timeseriesValuesByParameters",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<List<Timeseries>> getTimeseriesValuesByAccessParameterValuesDtos(@ApiParam(value = ""  )  @Valid @RequestBody List<AccessParameterValuesDto> accessParametersValuesDto,@ApiParam(value = "") @Valid @RequestParam(value = "interval", required = false) String interval);


    @ApiOperation(value = "Adds values to given Timeseries's. All Timeseries's must exists!", nickname = "putTimeseriesValuesByPersistenceParameterValuesDtos", notes = "", response = Timeseries.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Timeseries.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "unauthorized", response = Error.class),
        @ApiResponse(code = 404, message = "resource not found", response = Error.class),
        @ApiResponse(code = 200, message = "error", response = Error.class) })
    @RequestMapping(value = "/timeseriesValuesByParameters",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<List<Timeseries>> putTimeseriesValuesByPersistenceParameterValuesDtos(@ApiParam(value = ""  )  @Valid @RequestBody List<PersistenceParameterValuesDto> persistenceParametersValuesDto);

}
